name: Rollback Manual

on:
  workflow_dispatch:
    inputs:
      motivo:
        description: 'Motivo do rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: producao
    steps:
      - uses: actions/checkout@v4
      - name: Executar Rollback
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Motivo: ${{ github.event.inputs.motivo }}"
          chmod +x scripts/rollout.sh
          ./scripts/rollout.sh rollback
